languageCode = "es-es"
defaultContentLanguage = "es-es"
title = "DSSTI Shop"
baseurl = "http://example.org/"
#theme = "hugo-theme-bootstrap4"
custom_navbar = true
copyright = "&copy;2017 DSSTI"

[params.sharingicons]
    hide = "true"

[params.sidebar]
    about = "DSSTI Shop es su mejor proveedor de iluminación y material eléctrico"
    num_recent_posts = 5

[[menu.sidebar]]
    name = "Catalogo"
    url = "/catalogo/"
    weight = -100
